# Generated by Django 3.1.3 on 2021-04-15 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('work_place', models.CharField(blank=True, max_length=30, null=True)),
                ('degree', models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'Student'), (2, 'MAB'), (3, 'MAA'), (4, 'MCB'), (5, 'MCA'), (6, 'Professor')], default=0)),
                ('speciality', models.CharField(blank=True, max_length=50, null=True)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
