# Generated by Django 3.1.3 on 2021-04-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='enabled',
        ),
    ]
