# Generated by Django 3.2.3 on 2021-06-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='conference',
            name='place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
